var levels = [
        // these are maps
    ["xxxxxxxxxxxxxxxxxxxx", 
     "x             x    x", 
     "x             x  @ x", 
     "x                  x", 
     "x o                x", 
     "xxxxxx        xxxxxx", 
     "x                  x", 
     "x         o        x", 
     "x        xxx       x", 
     "x                  x", 
     "x o              o x", 
     "xxxxxx        xxxxxx", 
     "x                  x", 
     "x         o        x", 
     "x        xxx       x", 
     "x                  x", 
     "x                  x", 
     "x                  x", 
     "x o              o x", 
     "xxxxxx!!!xx!!!xxxxxx"],
    [
        'xxxxxxxxxxxxxxxxxxxx',
        'x@     !           x',
        'x                  x',
        'x      o           x',
        'x                  x',
        'x      !    o      x',
        'xxxxxxxx           x',
        'x                  x',
        'xo                 x',
        'xx                 x',
        'x                  x',
        'x      x      o    x',
        'x                  x',
        'xx                 x',
        'x     o            x',
        'x    xxxx          x',
        'x    x  x          x',
        'x  xxx             x',
        'x              o   x',
        'xxxxxxxxx!!!!!!x!!!x',
    ],
    [
        'xxxxxxxxxxxxxxxxxxxx',
        'x                  x',
        'x        o         x',
        'x                  x',
        'x                  x',
        'x       xxxx       x',
        'x    o        o    x',
        'x    x        x    x',
        'xxx      @       xxx',
        'x       xxxx       x',
        'x                  x',
        'x   !!!! o  !!!!   x',
        'x        x         x',
        'x                  x',
        'x        xx        x',
        'x     x      x     x',
        'xxx              xxx',
        'x                  x',
        'x         o        x',
        'xxxxxxxxxxxxxxxxxxxx',
    ],
    [
        'xxxxxxxxxxxxxxxxxxxx',
        'x         x        x',
        'x   x         o    x',
        'x      xxxxxxxxxxxxx',
        'xx                 x',
        'x     o            x',
        'x                  x',
        'xxx!!!!       o    x',
        'x        xxxxxxxx!!x',
        'x                  x',
        'x                  x',
        'x  xxxxxx o        x',
        'x       x!!!x      x',
        'x   o   x   x      x',
        'x           xxx    x',
        'xxxxxxxxx   x      x',
        'x                xxx',
        'x                  x',
        'x @                x',
        'xxxxxxxxxxxxxxxxxxxx',
    ],
    [
        'xxxxxxxxxxxxxxxxxxxx',
        'x                  x',
        'x    xxxxxxxxx     x',
        'x o  x         o   x',
        'xxxxxx             x',
        'x                xxx',
        'x          o       x',
        'x    xxxxxxxxxxxxxxx',
        'x        @         x',
        'xx                 x',
        'x                  x',
        'x            o     x',
        'xxxxxxx            x',
        'x                  x',
        'x!!!!!!!!!!!  !!!!!x',
        'x                  x',
        'x    o             x',
        'x                  x',
        'x           o      x',
        'xxxxxxxxxxxxxxxxxxxx',
    ],
    [
        'xxxxxxxxxxxxxxxxxxxx',
        'x   @x             x',
        'x xxxx   o         x',
        'x       xxx        x',
        'x                  x',
        'x!xxxx           o x',
        'x              xxxxx',
        'x    o             x',
        'x  xxxxxx          x',
        'x                  x',
        'x                  x',
        'x                  x',
        'xx                 x',
        'x                  x',
        'x   o              x',
        'x   x              x',
        'x       xxxxx      x',
        'x                  x',
        'xo               o x',
        'x!!!!!!!!!!!!!!!xx!x',
    ],
    ["xxxxxxxxxxxxxxxxxxxx", "x                  x", "x                 ox", "x                xxx", "x    x   x   x     x", "xx                 x", "x                  x", "x o                x", "xxxxxxx            x", "x@        xx       x", "x                  x", "x               o  x", "xxxxxx   xxxxxxxxxxx", "x    x             x", "x    x             x", "x  o x             x", "x xxxx             x", "x x                x", "x                o x", "xxxxxxxxx!!!!!!xxxxx"],
    [
        '!!!!!!!!!!!!!!!!!!!!',
        '!   @              !',
        '!                  !',
        '!                  !',
        '!                  !',
        '!    o             !',
        '!    x     o       !',
        '!                  !',
        '!                  !',
        '!             o    !',
        '!             x    !',
        '!                  !',
        '!       x          !',
        '!o                 !',
        '!x                 !',
        '!    o             !',
        '!                  !',
        '!                  !',
        '!       o          !',
        '!!!!!!!!!!!!!!!!!!!!',
    ],
    [
        'xxxxxxxxxxxxxxxxxxxx',
        'x@ xo      xo     ox',
        'xx xx      x       x',
        'x   x              x',
        'x x x  xxxxxxxxxxxxx',
        'x x                x',
        'x xxxxxxxx  xxxxxxxx',
        'x   ox             x',
        'xxx  x             x',
        'x                  x',
        'x                  x',
        'xx                 x',
        'xxxxx     o        x',
        'x        xxxx      x',
        'x     o            x',
        'x                  x',
        'x      o           x',
        'x                  x',
        'x o              o x',
        'xxxxxxxxxxxxxxxxxxxx',
    ],
    [
        '           xxxxxxxxx',
        '           x      @x',
        '           x o     x',
        '           x       x',
        'xxxxxxxxxxxx  xxxxxx',
        'x             x     ',
        'x      o      x     ',
        'x             x     ',
        'x  xxxxxxxxxxxxxxxxx',
        'x  xo   x          x',
        'x  x               x',
        'x                  x',
        'x      xx    o     x',
        'xxx  xxx           x',
        '  x  x             x',
        '  x                x',
        '  x                x',
        '  x  x             x',
        '  xo x         o   x',
        '  x!!xxxxxxxxxxxxxxx',
    ],
    ["xxxxxxxxxxxxxxxxxxxx", 
     "x                  x", 
     "x @      o         x", 
     "x                  x", 
     "x   o              x", 
     "xxxxxxx            x", 
     "x                  x", 
     "x           o      x", 
     "x                  x", 
     "x    o    o        x",
     "x                  x", 
     "x                  x", 
     "xo    xx           x", 
     "xxx                x", 
     "x                  x", 
     "x   xx       o     x", 
     "x                  x", 
     "x       xx         x", 
     "x                  x", 
     "x!!!!!!!!!!!xxx!!!!x"],
];